# Use postgres/example user/password credentials
version: '3.1'

services:
    nodejs-react-app:  
      image: ${IMAGE}
      PORTS:
      - 3080:3080
    db:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: example
    adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080