version: '3.8'
services:
    REACT-NODEJS-EXAMPLE:
      image: ${IMAGE}
      ports:
        - 8080:8080
    postgress:
      image: postgress:latest
      port:
        - 5432:5432
      environment:
        - POSTGRESS_PASSWORD=MY-PWD 
     
