version: '3.8'
services:
    nodejs-react-app:
      image: ${IMAGE}
      ports:
        - 3080:3080
    postgress:
      image: postgress
      port:
        - 5432:5432
      environment:
        - POSTGRESS_PASSWORD=my-pwd
     
