version: '3.8'
services:
    nodejs-react-app:
      image: mojoe277/nodejs-app:njr-1.0
      ports:
        - 8080:8080
    postgress:
      image: postgress:latest
      port:
        - 5432:5432
      environment:
        - POSTGRESS_PASSWORD=my-pwd
     
